# Import ingredients

In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import random
from tqdm.notebook import tqdm
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, plot_confusion_matrix
import spacy
import en_core_web_sm
from nltk.stem import WordNetLemmatizer 
import nltk
nltk.download('wordnet')
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

/usr/local/lib/python3.6/dist-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "

## Loading Data

In [ ]:
df = pd.read_pickle('final_project/Imdb_movie_reviews_database_cleaned_v1.pckl')

## Exploring the data - 1

In [ ]:
df.shape

(50000, 3)

In [ ]:
df

                                                 reviews  ...                                       review_clean
0      Bromwell High is a cartoon comedy. It ran at t...  ...  bromwell high cartoon comedy run time program ...
1      Homelessness (or Houselessness as George Carli...  ...  homelessness houselessness george carlin state...
2      Brilliant over-acting by Lesley Ann Warren. Be...  ...  brilliant act lesley ann warren best dramatic ...
3      This is easily the most underrated film inn th...  ...  easily underrated film inn brook cannon sure f...
4      This is not the typical Mel Brooks film. It wa...  ...  typical mel brook film much less slapstick mov...
...                                                  ...  ...                                                ...
49995  I occasionally let my kids watch this garbage ...  ...  occasionally let kid watch garbage understand ...
49996  When all we have anymore is pretty much realit...  ...  anymore pretty much reality tv show people mak...
49997  The basic genre is a thriller intercut with an...  ...  basic genre thriller intercut uncomfortable me...
49998  Four things intrigued me as to this film - fir...  ...  four thing intrigue film firstly star carly po...
49999  David Bryce's comments nearby are exceptionall...  ...  david bryce comment nearby exceptionally well ...

[50000 rows x 3 columns]

In [ ]:
# Check reviews to see if they correspond to sentiment.
df['reviews'][0]

'Bromwell High is a cartoon comedy. It ran at the same time as some other programs about school life, such as "Teachers". My 35 years in the teaching profession lead me to believe that Bromwell High\'s satire is much closer to reality than is "Teachers". The scramble to survive financially, the insightful students who can see right through their pathetic teachers\' pomp, the pettiness of the whole situation, all remind me of the schools I knew and their students. When I saw the episode in which a student repeatedly tried to burn down the school, I immediately recalled ......... at .......... High. A classic line: INSPECTOR: I\'m here to sack one of your teachers. STUDENT: Welcome to Bromwell High. I expect that many adults of my age think that Bromwell High is far fetched. What a pity that it isn\'t!'

In [ ]:
pos_reviews = df[df['sentiment']==1]['reviews']
neg_reviews = df[df['sentiment']==0]['reviews']
print("First 10 samples of positive reviews\n".format(),pos_reviews[:10])
print("First 10 samples of negative reviews\n".format(),neg_reviews[:10])

First 10 samples of positive reviews
 0    Bromwell High is a cartoon comedy. It ran at t...
1    Homelessness (or Houselessness as George Carli...
2    Brilliant over-acting by Lesley Ann Warren. Be...
3    This is easily the most underrated film inn th...
4    This is not the typical Mel Brooks film. It wa...
5    This isn't the comedic Robin Williams, nor is ...
6    Yes its an art... to successfully make a slow ...
7    In this "critically acclaimed psychological th...
8    THE NIGHT LISTENER (2006) **1/2 Robin Williams...
9    You know, Robin Williams, God bless him, is co...
Name: reviews, dtype: object
First 10 samples of negative reviews
 12500    Story of a man who has unnatural feelings for ...
12501    Airport '77 starts as a brand new luxury 747 p...
12502    This film lacked something I couldn't put my f...
12503    Sorry everyone,,, I know this is supposed to b...
12504    When I was little my parents took me along to ...
12505    "It appears that many critics find the idea of...
12506    The second attempt by a New York intellectual ...
12507    I don't know who to blame, the timid writers o...
12508    This film is mediocre at best. Angie Harmon is...
12509    The film is bad. There is no other way to say ...
Name: reviews, dtype: object

In [ ]:
# df is in order, must randomise
df = df.sample(frac=1, random_state=6).reset_index(drop=True)

In [ ]:
df.head()

                                             reviews  ...                                       review_clean
0  Having just finished reading the book "One of ...  ...  finish reading book one kind week ago think wo...
1  WEEE this is still jolly good fun! As with mos...  ...  weee still jolly good fun friend see movie hbo...
2  Well I guess I know the answer to that questio...  ...  well guess know answer question money bombard ...
3  This is easily one of the best movies of the 1...  ...  easily one best movie otto preminger direct fo...
4  The story is about Ankush (Abhay Deol) - who i...  ...  story ankush abhay deol professional marriage ...

[5 rows x 3 columns]

In [ ]:
pos_reviews = df[df['sentiment']==1]['reviews']
neg_reviews = df[df['sentiment']==0]['reviews']
print("First 10 samples of positive reviews\n".format(),pos_reviews[:10])
print("First 10 samples of negative reviews\n".format(),neg_reviews[:10])

First 10 samples of positive reviews
 1     WEEE this is still jolly good fun! As with mos...
3     This is easily one of the best movies of the 1...
4     The story is about Ankush (Abhay Deol) - who i...
12    Gene Tierney and Dana Andrews, who were both s...
13    A message movie, but a rather good one. Outsta...
14    The silent film masterpiece Battleship Potemki...
15    i loved this movie it was one of the years bes...
16    I suppose I always felt that Hotel du Nord was...
18    gone in 60 seconds is a very good action comed...
19    For a long time I did not know weather I liked...
Name: reviews, dtype: object
First 10 samples of negative reviews
 0     Having just finished reading the book "One of ...
2     Well I guess I know the answer to that questio...
5     This is the third parody of the scary movies a...
6     in fact,it's basically the same movie.and they...
7     Comedy Central has a habit of putting on great...
8     My comment is for the Russian version of Space...
9     Have you ever heard the saying that people "te...
10    I am never a big fan of Taiwan movie productio...
11    This movie had potential and I was willing to ...
17    Robert Montgomery-Myrna Loy farce about Loy (I...
Name: reviews, dtype: object

In [ ]:
df.tail(5)

                                                 reviews  ...                                       review_clean
49995  Troma founder, Lloyd Kaufman is The Crapkeeper...  ...  troma founder lloyd kaufman crapkeeper antholo...
49996  whereas the hard-boiled detective stories of D...  ...  whereas hard boil detective story dashiell ham...
49997  "Undercurrent" features a top-notch cast of wo...  ...  undercurrent feature top notch cast wonderful ...
49998  For those expecting the cover art and story ou...  ...  expect cover art story outline indicate anothe...
49999  I came across this movie on TV. I hadn't heard...  ...  come across movie tv heard almost change chann...

[5 rows x 3 columns]

## Vectorisation Feature Engineering
### Following steps borrowed from Jonathan Oheix "Detecting Bad Customer Reviews with NLP"

In [ ]:
# add sentiment anaylsis columns
from nltk.sentiment.vader import SentimentIntensityAnalyzer

sid = SentimentIntensityAnalyzer()
df["sentiments"] = df["reviews"].apply(lambda x: sid.polarity_scores(x))
df = pd.concat([df.drop(['sentiments'], axis=1), df['sentiments'].apply(pd.Series)], axis=1)

In [ ]:
df

                                                 reviews  ...  compound
0      Having just finished reading the book "One of ...  ...    0.9364
1      WEEE this is still jolly good fun! As with mos...  ...    0.7895
2      Well I guess I know the answer to that questio...  ...   -0.4044
3      This is easily one of the best movies of the 1...  ...    0.9184
4      The story is about Ankush (Abhay Deol) - who i...  ...    0.9992
...                                                  ...  ...       ...
49995  Troma founder, Lloyd Kaufman is The Crapkeeper...  ...    0.8709
49996  whereas the hard-boiled detective stories of D...  ...   -0.9811
49997  "Undercurrent" features a top-notch cast of wo...  ...    0.4890
49998  For those expecting the cover art and story ou...  ...    0.9929
49999  I came across this movie on TV. I hadn't heard...  ...   -0.4110

[50000 rows x 7 columns]

In [ ]:
# add number of characters column
df["nb_char"] = df["reviews"].apply(lambda x: len(x))

In [ ]:
df.head()

                                             reviews  ...  nb_char
0  Having just finished reading the book "One of ...  ...     1629
1  WEEE this is still jolly good fun! As with mos...  ...      418
2  Well I guess I know the answer to that questio...  ...     1227
3  This is easily one of the best movies of the 1...  ...      628
4  The story is about Ankush (Abhay Deol) - who i...  ...     2628

[5 rows x 8 columns]

In [ ]:
# add number of words column
df["nb_words"] = df["reviews"].apply(lambda x: len(x.split(" ")))

In [ ]:
df

                                                 reviews  ...  nb_words
0      Having just finished reading the book "One of ...  ...       274
1      WEEE this is still jolly good fun! As with mos...  ...        84
2      Well I guess I know the answer to that questio...  ...       218
3      This is easily one of the best movies of the 1...  ...       112
4      The story is about Ankush (Abhay Deol) - who i...  ...       482
...                                                  ...  ...       ...
49995  Troma founder, Lloyd Kaufman is The Crapkeeper...  ...       119
49996  whereas the hard-boiled detective stories of D...  ...       799
49997  "Undercurrent" features a top-notch cast of wo...  ...       101
49998  For those expecting the cover art and story ou...  ...       465
49999  I came across this movie on TV. I hadn't heard...  ...        95

[50000 rows x 9 columns]

Extract vector representations for every review. Gensim module creates a numerical vectors for each word in the corpus by using the contexts in which they appear (Word2Vec).

In [ ]:
# create doc2vec vector columns
from gensim.test.utils import common_texts
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

documents = [TaggedDocument(doc, [i]) for i, doc in enumerate(df["review_clean"].apply(lambda x: x.split(" ")))]

# train a Doc2Vec model with text data
model = Doc2Vec(documents, vector_size=5, window=2, min_count=1, workers=4)

# transform each document into a vector data
doc2vec_df = df["review_clean"].apply(lambda x: model.infer_vector(x.split(" "))).apply(pd.Series)
doc2vec_df.columns = ["doc2vec_vector_" + str(x) for x in doc2vec_df.columns]
df = pd.concat([df, doc2vec_df], axis=1)

In [ ]:
df

                                                 reviews  ...  doc2vec_vector_4
0      Having just finished reading the book "One of ...  ...          0.573996
1      WEEE this is still jolly good fun! As with mos...  ...          0.200012
2      Well I guess I know the answer to that questio...  ...          0.638754
3      This is easily one of the best movies of the 1...  ...          0.196561
4      The story is about Ankush (Abhay Deol) - who i...  ...          0.500467
...                                                  ...  ...               ...
49995  Troma founder, Lloyd Kaufman is The Crapkeeper...  ...          0.275315
49996  whereas the hard-boiled detective stories of D...  ...         -0.842359
49997  "Undercurrent" features a top-notch cast of wo...  ...          0.217802
49998  For those expecting the cover art and story ou...  ...          0.588338
49999  I came across this movie on TV. I hadn't heard...  ...          0.033701

[50000 rows x 14 columns]

In [ ]:
df.to_pickle("Imdb_doc2vec_v1.pckl")

In [ ]:
# add tf-idfs columns
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(min_df = 100)

In [ ]:
tfidf_result = tfidf.fit_transform(df["review_clean"]).toarray()

In [ ]:
tfidf_df = pd.DataFrame(tfidf_result, columns = tfidf.get_feature_names())

In [ ]:
tfidf_df.columns = ["word_" + str(x) for x in tfidf_df.columns]

In [ ]:
tfidf_df.index = df.index

In [ ]:
tfidf_df

       word_aaron  word_abandon  word_abc  ...  word_zombie  word_zone  word_zoom
0             0.0           0.0       0.0  ...          0.0        0.0        0.0
1             0.0           0.0       0.0  ...          0.0        0.0        0.0
2             0.0           0.0       0.0  ...          0.0        0.0        0.0
3             0.0           0.0       0.0  ...          0.0        0.0        0.0
4             0.0           0.0       0.0  ...          0.0        0.0        0.0
...           ...           ...       ...  ...          ...        ...        ...
49995         0.0           0.0       0.0  ...          0.0        0.0        0.0
49996         0.0           0.0       0.0  ...          0.0        0.0        0.0
49997         0.0           0.0       0.0  ...          0.0        0.0        0.0
49998         0.0           0.0       0.0  ...          0.0        0.0        0.0
49999         0.0           0.0       0.0  ...          0.0        0.0        0.0

[50000 rows x 5178 columns]

In [ ]:
tfidf_df.to_pickle("Imdb_tfidf.pckl")

In [ ]:
#df = pd.concat([df, tfidf_df], axis=1)